project_name: ServerStatus-Client
archives:
  - format: binary

builds:
  - env: [ CGO_ENABLED=0 ]
    goos: [ linux, android, darwin ]
    goarch: [ amd64, arm64 ]
    id: ServerStatus-Client
    dir: .
    main: ./cmd/client
    binary: client

  - env: [ CGO_ENABLED=0 ]
    goos: [ android ]
    goarch: [ arm64-v8a ]
    id: ServerStatus-Client-arm-v8a
    dir: .
    main: ./cmd/client
    binary: client-arm-v8a
